# Generated by Django 2.2.1 on 2019-05-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='main_blog',
            new_name='main_post',
        ),
    ]
