# Generated by Django 2.2.1 on 2019-05-29 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190527_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 22, 0)),
        ),
        migrations.AddField(
            model_name='mainpost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 22, 0)),
        ),
    ]
